### ISSUE TITLE
{lightgbm} v4.0.0 is coming

### ISSUE THREAD

**Issue by jameslamb** [nspyrison/cheem#2]
👋 Hello! I'm James, one of the maintainers of LightGBM.

We were excited to see `{cheem}` show up as a "reverse suggests" on https://cran.r-project.org/web/packages/lightgbm/index.html. Thanks so much for enhancing what users can do in R with LightGBM models!

First, I wanted to let you know that the next release of LightGBM (the entire project, including the R package) will be a major version release with significant breaking changes. See this discussion of v4.0.0: https://github.com/microsoft/LightGBM/issues/5153. We don't have a planned date for that release yet, as we have been struggling from a lack of maintainer attention / activity. But I expect it will be months not weeks from now.

Please open issues at https://github.com/microsoft/LightGBM/issues if there's anything we could do to make `{lightgbm}`  easier to use with  `{cheem}`.

Second, I wanted to share how you can test this project against `{lightgbm}`.

```shell
REPO_DIR="${HOME}/repos"

# install {cheem}'s Suggests dependencies
git clone \
    https://github.com/nspyrison/cheem.git \
    "${REPO_DIR}/cheem"
cd "${REPO_DIR}/cheem"
Rscript \
    --vanilla \
    -e "devtools::install_dev_deps()"

# build {lightgbm} R package from source and install it
git clone \
    --recursive \
    git@github.com:microsoft/LightGBM.git \
    "${REPO_DIR}/lgb-dev"

cd "${REPO_DIR}/lgb-dev"
sh build-cran-package.sh \
    --no-build-vignettes

R CMD INSTALL \
    --with-keep.source \
    ./lightgbm_*.tar.gz

# run R CMD check
cd "${REPO_DIR}/cheem"
R CMD build .
R CMD check --as-cran ./cheem_*.tar.gz
```

As of the most recent development version of `{lightgbm}` (https://github.com/microsoft/LightGBM/commit/44fe591a60d7427d64997c37b22768a92c97c47b), `R CMD check` shows some failing examples and tests.

Are you open to contributions that attempt to resolve these and make `{cheem}` compatible with both old and new versions of `{lightgbm}`?

Thanks very much for your time and consideration.

**Comment by nspyrison** [comment]
Hi James!

Thank you for working on/maintaining lightGBM.

Yes, I am open to such contributions, though I don't have a lot of time to devote to testing.


Cheers,
Nick
