### ISSUE TITLE
could not find function "basis_attr_df"

### ISSUE THREAD

**Issue by pbiecek** [nspyrison/cheem#3]
Hi,

in the `cheem --- version 0.3.0`
after calling
```
library(cheem)
 run_app()
```

I've get following warning:

```
Warning: Error in basis_attr_df: could not find function "basis_attr_df"
  205: <reactive:bas> [/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/cheem/shiny_apps/cheem/app.R#68]
```

I see that `cheem:::basis_attr_df` is not exported, so maybe this is the cause

**Comment by nspyrison** [comment]
Thank you @pbiecek. This takes precedence over CRAN checks. I will address this next.
